In [ ]:
import pandas as pd
import os


list_name = ["NEW KAZO sale master MAR'25.xlsx",
             "NEW KAZO sale master APR'25.xlsx",
             "NEW KAZO sale master MAY'25.xlsx",
             "NEW KAZO sale master JUN'25.xlsx",
             "NEW KAZO sale master JUL'25.xlsx",
             "NEW KAZO sale master AUG'25.xlsx",
             "NEW KAZO sale master SEP'25.xlsx",
             "NEW KAZO sale master OCT'25.xlsx",
            ]
all_list = []

for fill in list_name:
    temp_read = pd.read_excel(fill,sheet_name = "MAIN DATA",engine = 'openpyxl')

    temp_read['CUSTOMER_NAME'] = temp_read['CUSTOMER_NAME'].astype(str).str.strip().str.upper() 
    temp_read = temp_read.dropna(subset = ['Date'])
    temp_read = temp_read.iloc[:,0:33]
    all_list.append(temp_read)
df_final = pd.concat(all_list,ignore_index = True)
print("Data Appened successfully")

In [ ]:
df_final.head()

,Brand,Store Type,CUSTOMER_NAME,DESTINATION SITE,CHECK,BillNo.,Date,month,year,EAN Code,...,DEPARTMENT,Sale Type,Week NO,festival,Offer,SEASON,TMRP CHECK,CORE/ SEASON,UID,Dis%
0,KAZO,NaN,#REF!,#REF!,NaN,#REF!,#REF!,#REF!,#REF!,#REF!,...,NaN,NaN,NaN,NaN,NaN,NaN,#VALUE!,NaN,NaN,NaN
1,KAZO,NaN,SHREE RAM ENTERPRISES BHIWANI B,SHREE RAM ENTERPRISES BHIWANI B,NaN,S/24-25/1338,2025-03-22 00:00:00,Mar,2025,8903331834929,...,T Shirt,NaN,NaN,NaN,Flat50%,AW23,0,NaN,NaN,NaN
2,KAZO,NaN,SHREE RAM ENTERPRISES BHIWANI B,SHREE RAM ENTERPRISES BHIWANI B,NaN,S/24-25/1338,2025-03-22 00:00:00,Mar,2025,8903331835537,...,Top,NaN,NaN,NaN,Flat50%,SS23,0,NaN,NaN,NaN
3,KAZO,NaN,SHREE RAM ENTERPRISES BHIWANI B,SHREE RAM ENTERPRISES BHIWANI B,NaN,S/24-25/1338,2025-03-22 00:00:00,Mar,2025,8903331836404,...,T Shirt,NaN,NaN,NaN,Flat50%,AW23,0,NaN,NaN,NaN
4,KAZO,NaN,SHREE RAM ENTERPRISES BHIWANI B,SHREE RAM ENTERPRISES BHIWANI B,NaN,S/24-25/1347,2025-03-25 00:00:00,Mar,2025,8903331834912,...,T Shirt,NaN,NaN,NaN,Flat50%,AW23,0,NaN,NaN,NaN

In [ ]:
df = df_final.drop(0).reset_index(drop = True)

In [ ]:
df.tail()

,Brand,Store Type,CUSTOMER_NAME,DESTINATION SITE,CHECK,BillNo.,Date,month,year,EAN Code,...,DEPARTMENT,Sale Type,Week NO,festival,Offer,SEASON,TMRP CHECK,CORE/ SEASON,UID,Dis%
246,KAZO,NaN,SHYAM RETAIL STORES(SOR),SHYAM RETAIL REWARI NEW,NaN,CM\10053\10-25,2025-10-26 00:00:00,Oct,2025,8903331901614,...,Dress,NaN,NaN,NaN,Flat50%,SS24,0,NaN,NaN,NaN
247,KAZO,NaN,SHYAM RETAIL STORES(SOR),SHYAM RETAIL REWARI NEW,NaN,CM\10125\10-25,2025-10-27 00:00:00,Oct,2025,8903331879258,...,Dress,NaN,NaN,NaN,Flat50%,SS24,0,NaN,NaN,NaN
248,KAZO,NaN,SHYAM RETAIL STORES(SOR),SHYAM RETAIL REWARI NEW,NaN,CM\10131\10-25,2025-10-27 00:00:00,Oct,2025,8903331891922,...,Top,NaN,NaN,NaN,Flat50%,SS24,0,NaN,NaN,NaN
249,KAZO,NaN,SHYAM RETAIL STORES(SOR),SHYAM RETAIL REWARI NEW,NaN,CM\10146\10-25,2025-10-27 00:00:00,Oct,2025,8903331890055,...,T Shirt,NaN,NaN,NaN,Flat50%,SS24,0,NaN,NaN,NaN
250,KAZO,NaN,SHYAM RETAIL STORES(SOR),SHYAM RETAIL REWARI NEW,NaN,CM\10148\10-25,2025-10-27 00:00:00,Oct,2025,8903331876882,...,Shirt,NaN,NaN,NaN,Flat50%,SS24,0,NaN,NaN,NaN

In [ ]:
month_count = df['month'].value_counts()
print(month_count)

month
Jun      54
May      45
Mar      36
Apr      36
Jul      24
Sep      21
Aug      16
Oct      12
#REF!     7
Name: count, dtype: int64

In [ ]:
import pandas as pd


df['Date'] = pd.to_datetime(df['Date'], errors='coerce')


df = df.dropna(subset=['Date'])


df.loc[df['month'] == '#REF!', 'month'] = df['Date'].dt.strftime('%b')


month_order = ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct']
df['month'] = pd.Categorical(df['month'], categories=month_order, ordered=True)


df = df.sort_values('month').reset_index(drop=True)

print("Congratulation! #REF! errors are gone and months are sorted.")
print(df['month'].value_counts(sort=False))

Congratulation! #REF! errors are gone and months are sorted.
month
Mar    36
Apr    36
May    45
Jun    54
Jul    24
Aug    16
Sep    21
Oct    12
Name: count, dtype: int64

In [ ]:
df.tail()

,Brand,Store Type,CUSTOMER_NAME,DESTINATION SITE,CHECK,BillNo.,Date,month,year,EAN Code,...,DEPARTMENT,Sale Type,Week NO,festival,Offer,SEASON,TMRP CHECK,CORE/ SEASON,UID,Dis%
239,KAZO,NaN,SHYAM RETAIL STORES(SOR),SHYAM RETAIL REWARI NEW,NaN,CM\08923\10-25,2025-10-05,Oct,2025,8910000008192,...,Shirt,NaN,NaN,NaN,Flat50%,AW23,0,NaN,NaN,NaN
240,KAZO,NaN,SHYAM RETAIL STORES(SOR),SHYAM RETAIL REWARI NEW,NaN,CM\08779\10-25,2025-10-02,Oct,2025,8903331875823,...,Shirt,NaN,NaN,NaN,Flat50%,SS24,0,NaN,NaN,NaN
241,KAZO,NaN,SHYAM RETAIL STORES(SOR),SHYAM RETAIL REWARI NEW,NaN,CM\10146\10-25,2025-10-27,Oct,2025,8903331890055,...,T Shirt,NaN,NaN,NaN,Flat50%,SS24,0,NaN,NaN,NaN
242,KAZO,NaN,SHYAM RETAIL STORES(SOR),SHYAM RETAIL REWARI NEW,NaN,CM\09453\10-25,2025-10-17,Oct,2025,8903331900846,...,Top,NaN,NaN,NaN,Flat50%,SS24,0,NaN,NaN,NaN
243,KAZO,NaN,SHYAM RETAIL STORES(SOR),SHYAM RETAIL REWARI NEW,NaN,CM\10148\10-25,2025-10-27,Oct,2025,8903331876882,...,Shirt,NaN,NaN,NaN,Flat50%,SS24,0,NaN,NaN,NaN

In [ ]:
import pandas as pd 
import os
from openpyxl import load_workbook 

file_name = "final_net.xlsx"    
if os.path.exists(file_name):
    wb = load_workbook(file_name,read_only = True)
    sheet = wb['Sheet1']
    strt_rw = sheet.max_row
    wb.close()
    
    with pd.ExcelWriter(file_name,engine = 'openpyxl',mode = 'a',if_sheet_exists = 'overlay') as writer:
        df.to_excel(writer,index = False,sheet_name = 'Sheet1',startrow = strt_rw,header = True)
    print("Congratulation your file is append successfully")
else:
    df.to_excel(file_name,index = False, sheet_name = 'Sheet1')
    print("Congratulation your file is created successfully")

Congratulation your file is created successfully